name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: Staging

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_GRASS_0A44EA61E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'dist'
        env:
          NODE_VERSION: 18
          VITE_AUTH0_CLIENT_ID: ${{ vars.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_DOMAIN: ${{ vars.VITE_AUTH0_DOMAIN }}
          VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
          VITE_DEBUG: ${{ vars.VITE_DEBUG }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ vars.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_SHOPIFY_URL: ${{ vars.VITE_SHOPIFY_URL }}
